### ISSUE TITLE
clash配置文件出错

### ISSUE THREAD

**Issue by tsx3000** [freefq/free#92]
错误信息：
Parse config error: ProxyGroup Proxy: 'proxies[11]' expected type 'string', got unconvertible type '[]interface {}'

需要在proxies:下面的节点名后面加双引号

proxy-groups:
  # select 用来允许用户手动选择 代理服务器 或 服务器组
  # 您也可以使用 RESTful API 去切换服务器，这种方式推荐在 GUI 中使用
  - name: Proxy
    type: select
    proxies:
     - auto
     - github.com/freefq - 美国  9
     - github.com/freefq - 美国  10
     - github.com/freefq - 美国  11
     - github.com/freefq - 美国  12

**Comment by freefq** [comment]
原来是这个问题 谢谢提醒 马上修改

**Comment by tsx3000** [comment]
改为这样的可以通过

```
proxy-groups:
  - name: Proxy
    type: select
    proxies:
     - "auto"
     - "github.com/freefq - 美国  9"
     - "github.com/freefq - 美国  10"
     - "github.com/freefq - 美国  11"
     - "github.com/freefq - 美国  12"
     - "github.com/freefq%20-%20%E7%BE%8E%E5%9B%BD%20%2013"
     - "github.com/freefq%20-%20%E8%8B%B1%E5%9B%BD%20%2014"
```
